version: '3'
services:
  control_module:
    image: control_module:v1
    stdin_open: true
    tty: true
    ports:
      - 9010:9010
    networks:
      default:
        aliases:
          - mycontrol

  game_module:
    image: game_module:v1
    ports:
      - 9001:9001
    networks:
      default:
        aliases:
          - mygame

  player_module:
    image: player_module:v1
    ports:
      - 9000:9000
    networks:
      default:
        aliases:
          - myplayer